# Generated by Django 5.2.8 on 2025-12-01 15:58

import django.db.models.deletion
import portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FocusStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, unique=True)),
                ('total_sesh_day', models.IntegerField(default=0)),
                ('total_focus_time_day', models.FloatField(default=0.0)),
                ('times_phone_stopped_day', models.IntegerField(default=0)),
                ('total_sesh_week', models.IntegerField(default=0)),
                ('total_focus_time_week', models.FloatField(default=0.0)),
                ('times_phone_stopped_week', models.IntegerField(default=0)),
                ('last_day_reset', models.DateField(default=portal.models.get_current_date)),
                ('last_week_reset', models.DateField(default=portal.models.get_current_date)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supabase_id', models.CharField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('task', models.CharField(max_length=50)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quizzes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('correct_count', models.IntegerField()),
                ('total_questions', models.IntegerField()),
                ('accuracy', models.FloatField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.profile')),
            ],
        ),
    ]
