# Generated by Django 5.2.8 on 2025-12-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='detect_phones',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='detect_tabs',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='weekly_goal_hour',
            field=models.IntegerField(default=20),
        ),
    ]
