# Generated by Django 5.2.8 on 2025-12-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_profile_detect_phones_profile_detect_tabs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_report_generated',
            field=models.DateTimeField(default='1970-01-01 00:00:00'),
        ),
    ]
