# Generated by Django 5.2.8 on 2025-12-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_profile_last_report_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_report_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
