# Generated by Django 5.2.8 on 2025-12-06 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_profile_last_report_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='WrongQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('wrong_questions_data', models.JSONField()),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.quizzes')),
            ],
        ),
    ]
