# Generated by Django 5.2.8 on 2025-12-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_wrongquestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wrong_questions_amt',
            field=models.IntegerField(default=0),
        ),
    ]
